### ISSUE TITLE
Simplify your CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [aye-Soumya/deployment_test#5]
It is always good to try to simplify your code as much as possible. For the CSS, you can simplify by applying shared properties to multiple elements at once, rather than individually repeating the same property. The font-family and font-weight properties are shared by all elements, so the code can be simplified by applying them to a selector like html.

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}
```

Try to simplify any other shared properties you see in your CSS.
